### ISSUE TITLE
Role fails on Debian 12 due to missing python-ipaddr package.

### ISSUE THREAD

**Issue by Charlie-Root** [mrlesmithjr/ansible-frr#111]
**Describe the bug**
Role fails on Debian 12 due to missing python-ipaddr/python3-ipaddr package. Same as https://github.com/mrlesmithjr/ansible-frr/issues/72
 
**To Reproduce**

Create a Debian 12 VM
Create a playbook that includes the `mrlesmithjr.frr` role
The task fails with the following error: `fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'python-ipaddr' is available"}`

**Expected behavior**
The role should install FRR without errors.

**Screenshots**

TASK [mrlesmithjr.frr : Install FRR] ****************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'python-ipaddr' is available"}

**Additional context**

```
E: Unable to locate package python3-ipaddr
E: Unable to locate package python-ipaddr
```
https://packages.debian.org/search?suite=bookworm&arch=any&searchon=names&keywords=python-ipaddr
https://packages.debian.org/search?suite=bookworm&arch=any&searchon=names&keywords=python3-ipaddr

**Comment by luisepbueno** [comment]
I have the fix in this PR: https://github.com/mrlesmithjr/ansible-frr/pull/122
