### ISSUE TITLE
'frr_reload' is undefined

### ISSUE THREAD

**Issue by mwadman** [mrlesmithjr/ansible-frr#12]
Hi!
I'm getting the following issue when running this role:

```
TASK [ansible-frr : add python frr tools to install list] **********************
fatal: [host]: FAILED! => {"msg": "The conditional check 'frr_reload == true' failed. The error was: error while evaluating conditional (frr_reload == true): 'frr_reload' is undefined
The error appears to have been in '/etc/ansible/roles/ansible-frr/tasks/debian.yml': line 74, column 3, but may be elsewhere in the file depending on the exact syntax _problem.

The_ offending line appears to be:
- name: add python frr tools to install list
  ^ here

"}
```

I'm [not able to find](https://github.com/mrlesmithjr/ansible-frr/search?q=frr_reload&unscoped_q=frr_reload) any reference to this variable being set anywhere in the repository.

If I'm not missing something, would you mind describing how this variable is intended and I'll create a pull request.

Thanks!

**Comment by mrlesmithjr** [comment]
I think this is something @nertwork added. It is definitely missing as you mentioned. So, hopefully he can shed some light on this.

**Comment by mwadman** [comment]
Thanks!
