### ISSUE TITLE
Support for different CPU architectures - ARM?

### ISSUE THREAD

**Issue by ShaunDwyer** [mrlesmithjr/ansible-frr#2]
Hi,

I'm looking at using your role to deploy frr on a bunch of raspberry pis running raspbian stretch.

Would it be possible to include support for architecture other than amd64? 

From 'ansible -m setup' agasint a host, i see
"ansible_machine": "armv7l"
could perhaps be used to detect when to use armhf packages?

Cheers!
-Shaun

**Comment by mrlesmithjr** [comment]
@ShaunDwyer I'll definitely look into this.

**Comment by mrlesmithjr** [comment]
@ShaunDwyer Can you test with branch issue#2 ? Should be good to go but need to make sure.

**Comment by ShaunDwyer** [comment]
It works!

I'm configuring for just zebra+ospf daemons, and I'm seeing an error:

TASK [ansible-frr : debug] ****************************************************************************************************
fatal: [rpi1]: FAILED! => {"msg": "The conditional check '_frr_bgp_summary['stdout'] != \"\"' failed. The error was: error while evaluating conditional (_frr_bgp_summary['stdout'] != \"\"): 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/Users/sdwyer/Documents/Projects/dev/ansible/roles/ansible-frr/tasks/monitor.yml': line 42, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug: var=_frr_bgp_summary['stdout']\n  ^ here\n"}

its probably unrelated and probably my fault, but all the binaries install fine.

Thanks for the quick turnaround!

Cheers!
-Shaun

**Comment by mrlesmithjr** [comment]
Awesome news. Let me know what you find in regards to the error. If all is good then I will get this merged into Master.
