### ISSUE TITLE
Install from APT repo

### ISSUE THREAD

**Issue by nertwork** [mrlesmithjr/ansible-frr#29]
With newer versions of FRR, the community has released an apt-repo. Let's use the repo for any versions that are on it.

**Comment by mrlesmithjr** [comment]
Makes perfect sense!

**Comment by mrlesmithjr** [comment]
I assume this is it? https://deb.frrouting.org/

**Comment by nertwork** [comment]
Yes - I'll be working on that this week.

**Comment by mrlesmithjr** [comment]
Excellent!!!

**Comment by elcomtik** [comment]
I think this can be od ater https://github.com/mrlesmithjr/ansible-frr/pull/36 was merged

**Comment by mrlesmithjr** [comment]
@nertwork You good with closing this as well?

**Comment by nertwork** [comment]
Sounds good to me! Thanks for following up!
