### ISSUE TITLE
Documentation for this?

### ISSUE THREAD

**Issue by coop59** [mrlesmithjr/ansible-frr#57]
Hello Guys,

Is there any documentation for this by chance? I realize it's been here for a while but I am not as smart as you guys are and I need some help getting this going.

Thanks,
Michael

**Comment by nertwork** [comment]
Hello Michael,

There's documentation on the README - I know that it's kinda light. There's also plenty of documentation about FRR from their website. What are you missing here so that we can help get our documentation more streamlined. 

Thanks!
