### ISSUE TITLE
Role fails on Debian 11 due to missing `python-ipaddr` package.

### ISSUE THREAD

**Issue by peterkuiper** [mrlesmithjr/ansible-frr#72]
**Describe the bug**
Role fails on Debian 11 due to missing `python-ipaddr` package.

**To Reproduce**
1. Create a Debian 11 VM
2. Create a playbook that includes the `mrlesmithjr.frr` role
4. The task fails with the following error: `fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'python-ipaddr' is available"}`

**Expected behavior**
The role should install FRR without errors.

**Screenshots**

TASK [mrlesmithjr.frr : Install FRR] ****************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'python-ipaddr' is available"}

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: N/A
 - Version: latest

 **Additional context**

 Changing `python-ipaddr` in https://github.com/mrlesmithjr/ansible-frr/blob/097187e2e2f1c82c19a68241926048bf07ee2afb/tasks/debian.yml#L63 to `python3-ipaddr` fixes the error.

**Comment by arhue** [comment]
I have the same issue.

**Comment by sirhopcount** [comment]
Can we reopen this please? This is still an issue.

**Comment by elcomtik** [comment]
Yes, we can reopen. However it will be auto closed if no one step in as contributor for this feature.

**Comment by peterkuiper** [comment]
@elcomtik I'm happy to make a PR with the above fix but I'm not sure if it would break older Debian versions.

**Comment by elcomtik** [comment]
Package list should be defined in variables and included at beginning for each supported distribution. You may look at implementation of proposed functionality at mrlesmith/ansible-matiafb-galera-cluster.

**Comment by sirhopcount** [comment]
I have a pull request ready but the workflow seem to fail for an unrelated reason:
```
  Building wheel for ruamel-yaml-clib (setup.py): started
  Building wheel for ruamel-yaml-clib (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      sys.argv ['/tmp/pip-install-_ip6syqe/ruamel-yaml-clib_03f3eedea5c64338b247d834a1ef3aba/setup.py', 'bdist_wheel', '-d', '/tmp/pip-wheel-e0k5vido']
      test compiling /tmp/tmp_ruamel_ogwdrwmp/test_ruamel_yaml.c -> test_ruamel_yaml OK
      /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/dist.py:286: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated, consider using implicit namespaces instead (PEP 420).
```
https://github.com/sirhopcount/ansible-frr/actions/runs/3522233314/jobs/5904965166#step:4:295

So I think we might need to fix that first (I assume via a different issue/pull request).

**Comment by sirhopcount** [comment]
Python is not really my area of expertise but it seems to be an issue with `ruamel.yaml` and `ruamel.yaml.clib`. From what I can tell adding `python3-dev` to the docker containers would solve the issue but  there may be an other way to solve this by using a different version of as talked about here:

https://stackoverflow.com/a/68627053

Can someone with some more expertise confirm that. If simply adding `python3-dev` is enough I'll make a pull request for that change on [mrlesmithjr/dockerfiles](https://github.com/mrlesmithjr/dockerfiles).

**Comment by elcomtik** [comment]
@sirhopcount I'll update python requirements as I have experienced a similar issue due to outdated python packages. Please rebase your code ad test if issue persist

**Comment by elcomtik** [comment]
The tests were fixed today. Please do rebase.
