### ISSUE TITLE
Issue with Ubuntu 18.04

### ISSUE THREAD

**Issue by anuragbhatia** [mrlesmithjr/ansible-frr#8]
Getting following while running this role. 

```
TASK [ansible-frr : debian | Installing FRR 3.0.3] ************************************************************************************************************************
fatal: [devops01.muc.anuragbhatia.com]: FAILED! => {"changed": false, "msg": "Failed to download https://github.com/FRRouting/frr/releases/download/frr-3.0.3/frr_3.0.3-1_ubuntu18.04.1_amd64.deb, HTTP Error 404: Not Found"}
```

**Comment by mrlesmithjr** [comment]
@nertwork Is this something you have in the pipeline to resolve by chance? If not, I would be glad to resolve it.

**Comment by nertwork** [comment]
@mrlesmithjr This is something that is already resolved.
@anuragbhatia You have to change the FRR version - the default version doesn't work on ubuntu18.04 so just put this var in:
`frr_version: 6.0`
